import {
  Product,
  CategoryCook,
  AdditionalIngredient,
  CategoryDrink,
} from "./app";

export const products: Product[] = [
  {
    name: "Маргарита",
    category: "pizza",
    cost: 600,
    weight: 660,
    proteins: 11.1,
    fats: 7.3,
    carbohydrates: 46.3,
    kilocalories: 296,
    badge: ["fatty"],
  },
  {
    name: "Пепперони",
    category: "pizza",
    cost: 579,
    weight: 640,
    proteins: 12.7,
    fats: 10.4,
    carbohydrates: 47.3,
    kilocalories: 334,
    badge: ["spicy", "fatty"],
  },
  {
    name: "4 Сыра",
    category: "pizza",
    cost: 679,
    weight: 730,
    proteins: 10.5,
    fats: 6.4,
    carbohydrates: 41.7,
    kilocalories: 267,
    badge: ["fatty"],
  },
  {
    name: "Гриль-Гурме",
    category: "pizza",
    cost: 679,
    weight: 720,
    proteins: 10.4,
    fats: 9.2,
    carbohydrates: 43.3,
    kilocalories: 297,
  },
  {
    name: "Coca-Cola",
    category: "drink-soft",
    cost: 100,
    weight: 500,
    proteins: 10.4,
    fats: 9.2,
    carbohydrates: 43.3,
    kilocalories: 297,
  },
  {
    name: "Sprite",
    category: "drink-soft",
    cost: 100,
    weight: 500,
    proteins: 10.4,
    fats: 9.2,
    carbohydrates: 43.3,
    kilocalories: 297,
  },
  {
    name: "Fanta",
    category: "drink-soft",
    cost: 100,
    weight: 500,
    proteins: 10.4,
    fats: 9.2,
    carbohydrates: 43.3,
    kilocalories: 297,
  },
  {
    name: "Вода",
    category: "drink-soft",
    cost: 100,
    weight: 500,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    name: "Сок апельсиновый",
    category: "drink-soft",
    cost: 150,
    weight: 500,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    name: "Сок яблочный",
    category: "drink-soft",
    cost: 150,
    weight: 500,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    name: "Сок березовый",
    category: "drink-soft",
    cost: 150,
    weight: 500,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    name: "Чай черный",
    category: "drink-hot",
    cost: 150,
    weight: 300,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    name: "Чай зеленый",
    category: "drink-hot",
    cost: 150,
    weight: 300,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    name: "Чай каркаде",
    category: "drink-hot",
    cost: 150,
    weight: 300,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    name: "Пиво",
    category: "drink-alcoholic",
    cost: 150,
    weight: 300,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    name: "Вино",
    category: "drink-alcoholic",
    cost: 150,
    weight: 300,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    name: "Глинтвейн",
    category: "drink-alcoholic",
    cost: 150,
    weight: 300,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    name: "По-гавайски",
    category: "wok",
    cost: 229,
    weight: 370,
    proteins: 11.1,
    fats: 7.3,
    carbohydrates: 46.3,
    kilocalories: 296,
  },
  {
    name: "По-тайски",
    category: "wok",
    cost: 229,
    weight: 415,
    proteins: 11.1,
    fats: 7.3,
    carbohydrates: 46.3,
    kilocalories: 296,
    badge: ["calories"],
  },
  {
    name: "Классический",
    category: "wok",
    cost: 199,
    weight: 415,
    proteins: 11.1,
    fats: 7.3,
    carbohydrates: 46.3,
    kilocalories: 296,
    badge: ["calories", "spicy"],
  },
  {
    name: "Мария",
    category: "pasta",
    cost: 325,
    weight: 415,
    proteins: 11.1,
    fats: 7.3,
    carbohydrates: 46.3,
    kilocalories: 296,
    badge: ["calories"],
  },
  {
    name: "Делла Мамма",
    category: "pasta",
    cost: 395,
    weight: 415,
    proteins: 11.1,
    fats: 7.3,
    carbohydrates: 46.3,
    kilocalories: 296,
    badge: ["calories"],
  },
  {
    name: "Карбонара",
    category: "pasta",
    cost: 295,
    weight: 415,
    proteins: 11.1,
    fats: 7.3,
    carbohydrates: 46.3,
    kilocalories: 296,
    badge: ["calories"],
  },
];

export const whatToCook: CategoryCook[] = [
  {
    name: "Пицца",
    id: "pizza",
  },
  {
    name: "Вок",
    id: "wok",
  },
  {
    name: "Паста",
    id: "pasta",
  },
];

export const additionalIngredients: AdditionalIngredient[] = [
  {
    label: "Mоцарелла",
    category: ["pizza", "wok"],
    cost: 150,
    weight: 300,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    label: "Шампиньоны",
    category: ["pizza", "wok"],
    cost: 150,
    weight: 300,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    label: "Пепперони",
    category: ["pizza"],
    cost: 150,
    weight: 300,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    label: "Ветчина",
    category: ["pizza", "pasta"],
    cost: 150,
    weight: 300,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    label: "Aнанасы",
    category: ["pizza", "wok"],
    cost: 150,
    weight: 300,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    label: "Горгонзолла",
    category: ["pizza", "pasta"],
    cost: 150,
    weight: 300,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    label: "Бекон",
    category: ["pizza", "pasta"],
    cost: 150,
    weight: 300,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    label: "Грибы шиитаке",
    category: ["wok"],
    cost: 150,
    weight: 300,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    label: "Курица",
    category: ["wok"],
    cost: 150,
    weight: 300,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    label: "Дополнительный соус",
    category: ["wok"],
    cost: 150,
    weight: 300,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    label: "Креветки",
    category: ["wok"],
    cost: 150,
    weight: 300,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    label: "Лосось",
    category: ["wok"],
    cost: 150,
    weight: 300,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
  {
    label: "Пармезан",
    category: ["pasta"],
    cost: 150,
    weight: 300,
    proteins: 0,
    fats: 0,
    carbohydrates: 10,
    kilocalories: 100,
  },
];

export const categoryDrink: CategoryDrink[] = [
  {
    name: "Безалкогольные",
    id: "drink-soft",
  },
  {
    name: "Горяченькие",
    id: "drink-hot",
  },
  {
    name: "Алкогольные",
    id: "drink-alcoholic",
  },
];
